### ISSUE TITLE
Create User eXperience based on example 

### ISSUE THREAD

**Issue by philippabele** [philippabele/shift-change-with-angular-draft-b#12]
Pattern "Tag / Suche / Biete / Person"

Am 02.01 wird eine Spät-Schicht gesucht. Als Tausch wird ein Dienst am gleichen Tag um 05:45 Uhr angeboten. Die Anfrage wurde vom User Hotel Juliet (Nato Alphabet HJ).

Hier nun die gesamte Liste welche in WhatsApp fortlaufend aktualisiert wird.

02.01. (S) spät (B) 05:45 HJ
10.01. (S) früher (B) 10:45 YW
11.01. (S) früher (B) 10:45 YW
14.01. (S) 13:45 (B) 05:45 AT
21.01. (S) egal (B) Nacht HJ
24.01. (S) Früh (B) Nacht SR
30.01. (S) spät (B) Nacht HJ
31.01. (S) früher (B) Nacht RG
09.02. (S) früher (B) Nacht RG
14.02. (S) früher) (B) 14:15 NO 🆕
15.02. (S) früher (B) Nacht RG
17.02. (S) später oder früh (B) 1345 SR
22.02. (S) früher (B) Nacht RG
24.02. (S) spät (B) 0545 SR
25.02. (S) früher (B) Nacht HJ
28.02. (S) früher (B) 15.45 RG
29.02. (S) früher (B) Nacht RG

**Comment by nora-lhe** [comment]
- [x] First version of the design concept
- [x] User survey and evaluation
- [x] Incorporate feedback
